#!/bin/bash
if [ ! -d "spz" ]; then
    mkdir spz
fi

python3 src/main.py         \
    --game=$1               \
    --name=$2               \
    --iterations=25         \
    --elo                   \

