#!/bin/bash
if [ ! -d "spz" ]; then
    mkdir spz
fi

python3 src/main.py      \
    --train-model        \
    --game=$1            \
    --iterations=30      \
    --num-games=6        \
    --learning-rate=0.01 \
    --optimizer=adam     \
    --checkpoint=15      \
    --name=$2            \
    --epochs=5           \
    --mcts-searches=6    \
    --save-point=500
